name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2, build image, and run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/projects/docker-course-selling-app

            git pull origin main
            
            sudo docker stop course-selling-app || true
            sudo docker rm course-selling-app || true
            
            sudo docker build -t course-selling-app:latest .
            sudo docker run -d -p 80:8080 --name course-selling-app course-selling-app:latest
